export default data [
   {
     name: 'Bitcoin',
     symbol: '₿',
     rank: 1,
     age: 5673,
     color: '#fa9e32',
     png32: 'https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/32/btc.png',
     png64: 'https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/btc.png',
     webp32: 'https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/32/btc.webp',
     webp64: 'https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/btc.webp',
     exchanges: 190,
     markets: 2848,
     pairs: 873,
     categories: [],
     allTimeHighUSD: 73781.24185982272,
     circulatingSupply: 19726243,
     totalSupply: 19726243,
     maxSupply: 21000000,
     links: {
       website: 'https://bitcoin.org',
       whitepaper: 'https://bitcoin.org/bitcoin.pdf',        
       twitter: null,
       reddit: 'https://reddit.com/r/bitcoin',
       telegram: null,
       discord: null,
       medium: null,
       instagram: null,
       tiktok: null,
       youtube: null,
       linkedin: null,
       twitch: null,
       spotify: null,
       naver: null,
       wechat: null,
       soundcloud: null
     },
     code: 'BTC',
     rate: 63462.3309366344,
     volume: 31001121585,
     cap: 1251873361402,
     delta: {
       hour: 0.9963,
       day: 1.0068,
       week: 1.1024,
       month: 0.951,
       quarter: 0.99,
       year: 2.0945
     }
   },
   {
     name: 'Ethereum',
     symbol: 'Ξ',
     rank: 2,
     age: 3265,
     color: '#282a2a',
     png32: 'https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/32/eth.png',
     png64: 'https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/eth.png',
     webp32: 'https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/32/eth.webp',
     webp64: 'https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/eth.webp',
     exchanges: 331,
     markets: 6372,
     pairs: 3621,
     categories: [ 'smart_contract_platforms' ],
     allTimeHighUSD: 4861.28870081089,
     circulatingSupply: 118030520,
     totalSupply: 118030520,
     maxSupply: null,
     links: {
       website: 'https://ethereum.org/en/',
       whitepaper: 'https://github.com/ethereum/wiki/wiki/White-Paper',
       twitter: 'https://twitter.com/ethereum',
       reddit: 'https://reddit.com/r/ethereum',
       telegram: null,
       discord: 'https://discord.com/invite/CetY6Y4',        
       medium: null,
       instagram: null,
       tiktok: null,
       youtube: null,
       linkedin: null,
       twitch: null,
       spotify: null,
       naver: null,
       wechat: null,
       soundcloud: null
     },
     code: 'ETH',
     rate: 3419.774479043484,
     volume: 18068348976,
     cap: 403637760044,
     delta: {
       hour: 1.0003,
       day: 1.0193,
       week: 1.1095,
       month: 0.9581,
       quarter: 1.1024,
       year: 1.7693
     }
   },
   {
     name: 'Tether',
     rank: 3,
     age: 3428,
     color: '#e9f4f4',
     png32: 'https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/32/usdt.png',
     png64: 'https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/usdt.png',
     webp32: 'https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/32/usdt.webp',
     webp64: 'https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/usdt.webp',
     exchanges: 318,
     markets: 18691,
     pairs: 4933,
     categories: [ 'stablecoins', 'asset_backed_tokens' ],   
     allTimeHighUSD: 1.08372533074166,
     circulatingSupply: 112862180225,
     totalSupply: 112862180225,
     maxSupply: null,
     links: {
       website: 'https://tether.to',
       whitepaper: 'https://tether.to/wp-content/uploads/2015/04/Tether-White-Paper.pdf',
       twitter: 'https://twitter.com/tether_to',
       reddit: 'https://reddit.com/r/Tether',
       telegram: 'https://t.me/OfficialTether',
       discord: null,
       medium: null,
       instagram: null,
       tiktok: null,
       youtube: null,
       linkedin: null,
       twitch: null,
       spotify: null,
       naver: null,
       wechat: null,
       soundcloud: null
     },
     code: 'USDT',
     rate: 1.000367387671284,
     volume: 67536135724,
     cap: 112903644398,
     delta: {
       hour: 0.9998,
       day: 0.9985,
       week: 0.9997,
       month: 0.9969,
       quarter: 0.9991,
       year: 0.9984
     }
   },
   {
     name: 'BNB',
     rank: 4,
     age: 2547,
     color: '#f4bc2c',
     png32: 'https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/32/bnb.png',
     png64: 'https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/bnb.png',
     webp32: 'https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/32/bnb.webp',
     webp64: 'https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/bnb.webp',
     exchanges: 130,
     markets: 3741,
     pairs: 2813,
     categories: [ 'cex', 'smart_contract_platforms' ],      
     allTimeHighUSD: 719.9338032081794,
     circulatingSupply: 148930232,
     totalSupply: 148930232,
     maxSupply: 200000000,
     links: {
       website: 'https://www.binance.com/en/bnb?ref=Y6TC8MN4',
       whitepaper: 'https://academy.binance.com/en/articles/what-is-bnb?ref=Y6TC8MN4',
       twitter: 'https://twitter.com/binance',
       reddit: 'https://reddit.com/r/binance',
       telegram: 'https://t.me/BinanceExchange',
       discord: 'https://discord.com/invite/jE4wt8g2H2',     
       medium: 'https://medium.com/@binance',
       instagram: 'https://instagram.com/Binance',
       tiktok: 'https://www.tiktok.com/@binance',
       youtube: 'https://www.youtube.com/binanceyoutube',    
       linkedin: 'https://www.linkedin.com/company/binance', 
       twitch: null,
       spotify: null,
       naver: null,
       wechat: null,
       soundcloud: null
     },
     code: 'BNB',
     rate: 570.9328216956867,
     volume: 1437629983,
     cap: 85029157591,
     delta: {
       hour: 0.9961,
       day: 1.0221,
       week: 1.1044,
       month: 0.939,
       quarter: 1.0385,
       year: 2.3463
     }
   },
   {
     name: 'Solana',
     rank: 5,
     age: 1555,
     color: '#7370e8',
     png32: 'https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/32/sol.png',
     png64: 'https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/sol.png',
     webp32: 'https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/32/sol.webp',
     webp64: 'https://lcw.nyc3.cdn.digitaloceanspaces.com/production/currencies/64/sol.webp',
     exchanges: 91,
     markets: 1822,
     pairs: 1288,
     categories: [ 'smart_contract_platforms' ],
     allTimeHighUSD: 259.8360337991446,
     circulatingSupply: 464185716,
     totalSupply: 580294264,
     maxSupply: null,
     links: {
       website: 'https://solana.com/',
       whitepaper: 'https://solana.com/docs',
       twitter: 'https://twitter.com/solana',
       reddit: 'https://reddit.com/r/solana',
       telegram: 'https://t.me/solana',
       discord: 'https://discord.com/invite/kBbATFA7PW',     
       medium: 'https://medium.com/solana-labs',
       instagram: 'https://www.instagram.com/solana_updates',
       tiktok: null,
       youtube: 'https://youtube.com/@SolanaFndn',
       linkedin: null,
       twitch: null,
       spotify: null,
       naver: null,
       wechat: null,
       soundcloud: null
     },
     code: 'SOL',
     rate: 156.0768787777806,
     volume: 3859135967,
     cap: 72448657726,
     delta: {
       hour: 1.0001,
       day: 1.0211,
       week: 1.093,
       month: 1.0767,
       quarter: 1.1097,
       year: 5.6108
     }
   }
 ]

 